### ISSUE TITLE
Replace native notifications

### ISSUE THREAD

**Issue by rickfrancisco** [foex-open-source/fos-notifications#1]
Hi.  I'd like to know if it possible we replace native notifications by this plugin.
Thanks.

Ricardo

**Comment by stefandobre** [comment]
Hi Ricardo,

this is not currently possible, but we plan to introduce this functionality in the next version of FOS.
Thanks for the suggestion!

**Comment by stefandobre** [comment]
This functionality is now available.
Simply instantiate the plugin on the global page on page load, and specify Action: Convert Native APEX Notifications.

You can download the newest version of the demo app and all plug-ins [here](https://fos.world/).

**Comment by rickfrancisco** [comment]
Thanks Stefan! I'll check it out.
